### ISSUE TITLE
Node-pool response always claims a node-pool has a single accelerator, even when it really has more.

### ISSUE THREAD

**Issue by thorkilds** [googleapis/google-cloud-java#3722]
Given a node-pool like this (output from gcloud):

```yaml
autoscaling:
  enabled: true
  maxNodeCount: 1
config:
  accelerators:
  - acceleratorCount: '2'
    acceleratorType: nvidia-tesla-p100
  diskSizeGb: 200
  diskType: pd-standard
  imageType: COS
  labels:
    consumer: batch
  machineType: custom-32-212992
  minCpuPlatform: Automatic
  oauthScopes:
  - [... lots of scopes ... ]
  preemptible: true
  serviceAccount: default
instanceGroupUrls:
- https://www.googleapis.com/compute/v1/projects/....
management: {}
name: mul-seq2seq-large
status: RUNNING
version: 1.10.7-gke.2
```
(scopes and instanceGroupUris shortened for brevity)

then I expect:
```java
NodePool nodepool = clusterManagerClient.getNodePool(projectId, zone, clusterName, "mul-seq2seq-large");
System.out.println(nodepool.getConfig().getAcceleratorsCount());
```
to return 2 (as there are 2 gpus attached), but the API actually answers 1 ! Calling nodepool.getConfig().getAcceleratorsList() also gives you a list of a single entry with the name of the gpu chosen. I have not tried to have different gpus on a node (if it might have merged them somehow).
