### ISSUE TITLE
Can't connect to datastore emulator in cloudbuild

### ISSUE THREAD

**Issue by lopezm94** [googleapis/google-cloud-java#4478]
I'm trying to run the datastore emulator inside cloudbuild but haven't got around a way to make my application connect to it.

This is my cloudbuild.yam file:

```yaml
- name: 'gcr.io/cloud-builders/docker'
  args:
    - run
    - --entrypoint
    - "gcloud"
    - --network
    - cloudbuild
    - --name
    - ds
    - --hostname
    - ds
    - -p
    - 8082:8081
    - -d
    - google/cloud-sdk:latest
    - beta
    - emulators
    - datastore
    - start
    - --project=dev
    - --host-port=ds:8081
    - --data-dir=./opt/data
    - --store-on-disk
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        cp .cloudbuild.m2.settings.xml /root/.m2/settings.xml && mvn clean package
  env:
  - 'DATASTORE_DATASET=dev'
  - 'DATASTORE_EMULATOR_HOST=http://ds:8082'
  - 'DATASTORE_EMULATOR_HOST_PATH=http://ds:8082/datastore'
  - 'DATASTORE_HOST=http://ds:8082'
  - 'DATASTORE_PROJECT_ID=dev'
```

(If I don't use `http://`  before `ds` then I get invalid schema, it is only allowed on localhost)

This is the error I get when executing package tests:

```
Step #5: [ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.134 s <<< FAILURE! - in com.myapp.service.MyServiceIntegrationTests
Step #5: [ERROR] create(com.myapp.service.MyServiceIntegrationTests)  Time elapsed: 17.681 s  <<< ERROR!
Step #5: com.google.cloud.datastore.DatastoreException: I/O error
Step #5: 	at com.myapp.service.MyService.create(MyService.kt:66)
Step #5: Caused by: com.google.datastore.v1.client.DatastoreException: I/O error
Step #5: 	at com.myapp.service.MyService.create(MyService.kt:66)
Step #5: Caused by: java.net.ConnectException: Connection refused (Connection refused)
Step #5: 	at com.myapp.service.MyService.create(MyService.kt:66)
```

**Comment by ajaaym** [comment]
@lopezm94 can you please try with ```'DATASTORE_EMULATOR_HOST=http://localhost:8082'```?

**Comment by lopezm94** [comment]
Made the changes but the same error is thrown

```yaml
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
        cp .cloudbuild.m2.settings.xml /root/.m2/settings.xml && mvn clean package
  env:
  - 'DATASTORE_DATASET=dev'
  - 'DATASTORE_EMULATOR_HOST=http://localhost:8082'
  - 'DATASTORE_EMULATOR_HOST_PATH=http://ds:8082/datastore'
  - 'DATASTORE_HOST=http://ds:8082'
  - 'DATASTORE_PROJECT_ID=dev'
```
